### ISSUE TITLE
Error on Anki 2.1.26

### ISSUE THREAD

**Issue by Willz7** [iamjustkoi/LeechToolkit#1]
![image](https://user-images.githubusercontent.com/5053219/193483427-5a9c9b1c-c889-47db-86fa-4e4fd1763c0f.png)

**Comment by iamjustkoi** [comment]
Oh shoot, this might still have some other issues pop up, but here's a patch to disable the sync features for until I can get another test run for 2.1.26.

Sorry the issue's popped up and thanks for reporting it!

[v1.0.3-anki2.1.26](https://github.com/iamjustkoi/LeechToolkit/releases/tag/v1.0.3-anki2.1.26)

**Comment by Willz7** [comment]
> Oh shoot, this might still have some other issues, too, but here's a patch to disable the sync features for until I can get another test run for 2.1.26.
> 
> Sorry the issue's popped up and thanks for reporting it!
> 
> [v1.0.3-anki2.1.26](https://github.com/iamjustkoi/LeechToolkit/releases/tag/v1.0.3-anki2.1.26)

I got another error when trying to install the addon

![image](https://user-images.githubusercontent.com/5053219/193516585-a6b775e6-e8c7-4486-b80b-3153ec8973ad.png)

**Comment by Willz7** [comment]
@iamjustkoi, I have deleted any trace of the leech toolkit addon in the addon folder. I have also tried both installing the zip folder leechToolKit-1 and LeechToolkit-1.0.3-anki2.1.26.ankiaddon, but it kept giving me the previous error that I posted about not able to find "LeechToolKit-1" in the source. I tried to find line 211 in LoadAddons in the zipped folder.

I also tried installing via Ankiaddon however I get an error "failed to execute script runanki" which I think is an error with old Anki version.

**Comment by iamjustkoi** [comment]
@Willz7 
Oh actually, sorry, that might still be something on my end!
If you try installing the addon without any extras in the name, so the addon's filename would be:
>LeechToolkit.ankiaddon

It might be able to successfully install it.

I didn't think about how Anki might handle filenames during install when I was naming it, to be honest.

I re-uploaded the file for the patch release if you want to just grab it from there, again, too:

[v1.0.3-anki2.1.26](https://github.com/iamjustkoi/LeechToolkit/releases/tag/v1.0.3-anki2.1.26)

Hope that works!

**Comment by Willz7** [comment]
@iamjustkoi 

I still get the same error. I have tried the pre-release and latest version. I will do more testing on other anki version.

![image](https://user-images.githubusercontent.com/5053219/193715688-ab5de4b2-e58c-4c2e-9bad-4007c51b067d.png)

**Comment by iamjustkoi** [comment]
@Willz7 
> I still get the same error. I have tried the pre-release and latest version. I will do more testing on other anki version.

Shoot, I'm sorry to hear that. 
It might also help to have a look at the debug info in Anki's about page. 

I also uploaded one more test patch to see if that might work, this time I updated the manifest to see if Anki's maybe not recognizing the add-on's package name. 
I'm having trouble running into the issue on my end, so thanks for sticking along with the whole process!

Either way, I'll keep trying to see if there's anything I can do, too.

[v1.0.3-anki2.1.26](https://github.com/iamjustkoi/LeechToolkit/releases/tag/v1.0.3-anki2.1.26) --(re-uploaded)

**Comment by Willz7** [comment]
> @iamjustkoi
> 
> I still get the same error. I have tried the pre-release and latest version. I will do more testing on other anki version.
> 
> ![image](https://user-images.githubusercontent.com/5053219/193715688-ab5de4b2-e58c-4c2e-9bad-4007c51b067d.png)

Hi @iamjustkoi, thank you for fixing the above issue.

I have two issue 

![image](https://user-images.githubusercontent.com/5053219/193951491-6854701b-6ac1-40d4-903b-cd5a1c770463.png)
This issue happened when I tried to go to the Leech Toolkit option to try and change some settings.

![image](https://user-images.githubusercontent.com/5053219/193952196-32d593c1-28f3-469f-891d-3e27d4f166d1.png)

This issue occurred when trying to click the toggle option to access the lapse option in the deck.

**Comment by iamjustkoi** [comment]
@Willz7 Defs! Glad to hear that one's been fixed.
Uploaded another patch for the other issues, too:

[v1.0.3-anki2.1.26-2](https://github.com/iamjustkoi/LeechToolkit/releases/tag/v1.0.3-anki2.1.26-2)

Hope that works out!

**Comment by iamjustkoi** [comment]
Released a temporary patch for 2.1.26 or below, will need to check up on it and hopefully it isn't something that ends up being permanent, maybe.

Either way, closing for now but feel free to post if you have any follow ups, and thanks for reporting!
