### ISSUE TITLE
Deactivate notifications

### ISSUE THREAD

**Issue by Ankilli** [iamjustkoi/LeechToolkit#12]
Hey there :)

it would be nice if one could turn off notifications during reviews.

Looks like everything else works like a charm so far! 👍

**Comment by iamjustkoi** [comment]
Hi hi!
Yeah, I could defs expose a toggle for the toast notification in options! Will try to add that in for the next release. Thanks for the suggestion!

If you don't want to wait too long for right now, there's also a variable in the meta.json file (same as the other thread but for easy reference: Tools > Add-on's > Leech Toolkit > All Files > meta.json) you can edit that can disable/enable the toast notification called `"tooltipEnabled"`. If you set that from `true` to `false` you should be good to go!

> Looks like everything else works like a charm so far! 👍

Very nice to hear! Happy studies! :D

**Comment by Ankilli** [comment]
Hmm changing  "tooltipEnabled" to false doesn't change anything I'm afraid 🤷😅
(closed Anki for the change, opened the .json in a texteditor, saved the file, and started Anki afterwards).

**Comment by iamjustkoi** [comment]
Oh, that's a shame. Guess I left some hanging variables in there, sorry about that! 

Will try and fix that along with the extra option for the next release, then.

**Comment by iamjustkoi** [comment]
Added with the latest release, thanks for the suggestion! 👍
