### ISSUE TITLE
Found this new error after updating today. Happens on opening of Anki.

### ISSUE THREAD

**Issue by Kosezu** [iamjustkoi/LeechToolkit#13]
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-16 15:33:52
Add-ons possibly involved: ⁨Leech Toolkit⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.sync", line 112, in on_future_done
  File "aqt.main", line 990, in on_collection_sync_finished
  File "_aqt.hooks", line 4595, in __call__
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/sync.py", line 80, in sync_collection
    toolkit_configs: dict = manager.get_all_configs()
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 71, in get_all_configs
    toolkit_configs[f'{deck_name_id.id}'] = merge_fields(self.config.get(str(config_id), {}), self.config)
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 26, in merge_fields
    config[field] = merge_fields(config[field], default_copy[field])
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 26, in merge_fields
    config[field] = merge_fields(config[field], default_copy[field])
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 26, in merge_fields
    config[field] = merge_fields(config[field], default_copy[field])
  [Previous line repeated 983 more times]
  File "/Users/cso/Library/Application Support/Anki2/addons21/368380974/src/config.py", line 21, in merge_fields
    default_copy = default_config.copy()
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by iamjustkoi** [comment]
Darn, sorry this's popped up for you and thanks for the report!

I'm having a bit of difficulty reproducing this on my end, to be honest.

Would you mind also sharing your current debug info for Anki?
(Can get to it via: `Help -> About -> Copy Debug Info`)
It might also be useful to see what your current settings are, if you'd be alright with sending the add-on's meta.json file my way, too (`Tools -> Add-ons -> Leech Toolkit -> View Files -> meta.json`). 

The debug info might be enough, actually, but just want to get as much context as I can, you know.

Going to probs be pretty busy over the next few days, but I'll try to push something out as soon as I can!

**Comment by Kosezu** [comment]
Here is the debug into:

    
    Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
    Platform: macOS-13.1-x86_64-i386-64bit
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-12-16 15:33:52
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['ResetEZ', 0, 'None', '']
    '' ['experimentalCardEaseFactor', 0, 'None', '']
    AJT Flexible Grading ['1715096333', 2022-12-15T17:36, 'None', mod]
    Add Hyperlink ['318752047', 2022-05-23T06:16, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2022-09-29T06:32, 'None', mod]
    Agent Orange Pseudo-Fuzz Defoliator ['175851166', 2020-11-19T21:21, 'None', '']
    AnkiConnect ['2055492159', 2022-09-18T17:11, 'None', '']
    Ankicord - Discord Rich Presence ['1828536813', 2022-05-03T02:50, 'None', mod]
    Another Retreat ['1481634779', 2018-12-14T16:22, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T14:11, 'None', '']
    Bury Cousins related cards that arent siblings ['1072815885', 2021-07-19T18:23, 'None', '']
    Bury related notes ['413416269', 2020-04-03T00:55, 'None', '']
    Card Retirement ['1972853015', 2021-08-07T09:17, 'None', mod]
    Cardistry 2 Dynamically Adjust New Cards ['1535078906', 2020-09-03T13:52, 'None', mod]
    Clickable Tags v20 original ['380714095', 2022-01-30T14:58, 'None', '']
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-23T14:03, 'None', '']
    Correct Answers Graph ['993120073', 2022-03-14T13:52, 'None', '']
    Custom Styles font color background colour classes ['1899278645', 2021-03-02T16:41, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T02:12, 'None', '']
    Deck Counts NowLater ['1836212767', 2020-09-09T08:33, 'None', '']
    Delay Overdue Cards ['43919973', 2020-08-16T15:10, 'None', '']
    Delay siblings ['1369579727', 2022-06-03T16:05, 'None', mod]
    Disable fading between cards ['1533933651', 2019-07-16T16:19, 'None', '']
    Ease Factor Histogram ['494944895', 2019-05-01T01:34, 'None', '']
    Fastbar- with nightmode support ['46611790', 2022-11-28T05:10, 'None', '']
    Five Finger Silver New Answer Button Graph ReLrn Stats ReMemorize Plan9-0 ['2047355215', 2019-06-05T00:43, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T09:06, 'None', '']
    Hint Hotkeys ['1844908621', 2019-07-15T23:45, 'None', '']
    Japanese Help Launcher  ['103383488', 2019-03-12T20:59, 'None', '']
    Japanese Pitch Accent Notes ['625243622', 2019-01-16T20:24, 'None', mod]
    Japanese Pitch Accent ['148002038', 2022-03-26T02:00, 'None', '']
    Japanese Pronunciation  Pitch Accent ['932119536', 2019-08-13T20:51, 'None', mod]
    Japanese Support ['3918629684', 2022-03-13T20:32, 'None', mod]
    Japanese Text Cleaner ['1852987770', 2019-07-12T17:32, 'None', '']
    Leaderboard ['41708974', 2022-05-12T02:46, 'None', mod]
    Learn now  Grade now ['1021636467', 2022-12-13T05:13, 'None', '']
    Leech Toolkit ['368380974', 2022-12-19T06:17, 'None', '']
    Mac OSX Dictionary Lookup ['2059332871', 2022-11-06T22:52, 'None', '']
    Mature Tag ['17741639', 2019-01-30T15:01, 'None', '']
    MecabUnidic ['13462835', 2019-08-24T16:46, 'None', '']
    Migaku Vacation ['Migaku Vacation', 2020-12-25T07:48, 'None', mod]
    More Decks Stats and Time Left ['1556734708', 2022-10-09T05:05, 'None', mod]
    More Overview Stats ['2116130837', 2022-09-16T10:56, 'None', '']
    No Distractions Full Screen Clean review interface  TabletTouch support ['1049863218', 2020-08-13T15:59, 'v4.1.8', mod]
    Open Added Today from Reviewer ['861864770', 2019-02-22T16:06, 'None', '']
    Postpone cards review ['1152543397', 2021-02-13T08:47, 'None', '']
    Pretzel Logic Retention Benchmarking ['1168065472', 2020-04-24T20:13, 'None', mod]
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-28T23:26, 'None', '']
    Push Paradox Sibling Cardistry ['1797395052', 2020-04-03T21:40, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-12-13T06:14, '20.12.13i151', '']
    Replay audio from editor ['1154817210', 2019-07-11T15:36, 'None', '']
    Reschedule in Reviewer ['1714744747', 2019-07-11T15:36, 'None', '']
    Reset Ease Automatically ['12081346', 2022-11-15T05:09, 'None', mod]
    Review Heatmap ['1771074083', 2022-06-29T18:43, 'None', '']
    Reviewer Context Menu ['281854631', 2019-01-25T15:09, 'None', '']
    Separate Learn and Relearn in the Answer Buttons graph 21 ['403491806', 2019-11-08T18:52, 'None', '']
    Special Fields ['1102281552', 2022-11-21T17:49, 'None', mod]
    Statistics for Note Types Card Types and Tags ['16703369', 2022-03-14T14:14, 'None', '']
    Straight Reward ['957961234', 2022-12-12T05:49, 'None', '']
    Throughput Histoical ['485345973', 2019-08-17T21:29, 'None', '']
    Time Spent Creating Cards ['1178407876', 2020-07-01T13:08, 'None', '']
    Touch Wood Show New Cards Left Hint ['1498273991', 2020-04-03T21:37, 'None', '']
    Trigger and actions change one card depending on what occurs on another card ['1981494159', 2021-10-18T01:32, 'None', mod]
    True Retention ['613684242', 2017-11-19T12:43, 'None', '']
    WaniKani Syncroniser ['987024389', 2019-04-23T05:27, 'None', mod]
    add-on dialog searchfilter bar ['561945101', 2021-12-05T12:28, 'None', '']
    allow narrower main window reduce minimum width ['1685562426', 2019-07-03T18:52, 'None', '']
    anki-forvo-dl - Forvo Pronunciation Downloader fully automatic ['858591644', 2022-07-31T04:26, 'None', '']
    autoLapseNewInterval  automatically adjust the new interval after a lapse ['372281481', 2022-09-28T00:26, 'None', '']
    avgEase for Anki  2141 ['1129477042', 2021-06-27T04:58, 'None', '']
    bury future new sibs ['930365039', 2019-11-24T22:39, 'None', '']
    confirm deletion ['263363568', 2019-04-13T15:58, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1021636467 103383488 1049863218 1072815885 1102281552 1129477042 1136455830 1152543397 1154817210 1168065472 1172858842 1178407876 12081346 13462835 1369579727 148002038 1481634779 1498273991 1508357010 1533933651 1535078906 1556734708 16703369 1685562426 1714744747 1715096333 175851166 1771074083 17741639 1797395052 1828536813 1836212767 1844908621 1852987770 1899278645 1972853015 1981494159 2047355215 2055492159 2059332871 2116130837 225180905 24411424 263363568 266436365 281854631 318752047 368380974 372281481 380714095 3918629684 403491806 413416269 41708974 43919973 46611790 485345973 494944895 561945101 613684242 625243622 831846358 858591644 861864770 930365039 932119536 957961234 987024389 993120073
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['No Penalties or Boosting', 0, 'None', '']
    '' ['PassFailJP', 0, 'None', '']
    '' ['autoLapseNewIntervalOLD', 0, 'None', '']
    '' ['autoLearningSteps', 0, 'None', '']
    AJT Pitch Accent ['1225470483', 2022-01-04T12:33, 'None', '']
    Anki Simulator ['817108664', 2021-08-07T12:24, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T17:20, 'v1.1.3', '']
    Anki-redesign ['308574457', 2022-10-27T17:36, 'None', '']
    Auto Ease Factor ['1672712021', 2021-03-21T11:11, 'None', mod]
    Backup Key ['1790131139', 2019-03-01T14:48, 'None', '']
    Bulk-Generate Japanese Vocab Frequency Ranking ['1612642956', 2019-03-10T19:31, 'None', mod]
    Coronavirus Tracker ['1313091126', 2020-04-22T03:11, 'None', '']
    CrowdAnki JSON exportimport Edit history Collaborate on deck creation ['1788670778', 2022-05-27T14:32, 'None', '']
    Enhance main window ['877182321', 2022-06-28T19:44, 'None', '']
    HoochieBaby Queue Controller  Day-Lrn Q ['1847358755', 2020-11-22T18:54, 'None', '']
    HoochieMama Randomize Rev Queue ['1460733408', 2020-06-03T06:17, 'None', '']
    HoochiePapa Randomize New Queue ['1173108619', 2020-04-24T20:17, 'None', '']
    Increase autosave frequency ['786971082', 2022-04-07T18:56, 'None', '']
    Japanese Card Randomizer ['1476821676', 2022-06-16T19:39, 'None', '']
    Japanese Example Sentences ['2413435972', 2019-02-21T22:32, 'None', mod]
    Kakijun - Kanji stroke order ['1250448937', 2020-05-14T17:58, 'None', '']
    Kanji Grid ['909972618', 2019-01-10T18:36, 'None', '']
    KanjiEaters Bulk-Generate Japanese OnYomi Phonetics ['1226813725', 2019-05-11T17:06, 'None', '']
    Mental Pause No bonus for being late ['1707633456', 2020-04-17T00:05, 'None', '']
    Migaku Anki Add-on ['1846879528', 2022-05-21T03:06, 'None', mod]
    Migaku Dictionary ['Migaku Dictionary', 2020-12-16T17:46, 'None', mod]
    Migaku Flexible Grading ['Migaku Flexible Grading', 0, 'None', '']
    Migaku Japanese ['Migaku Japanese', 2020-12-16T14:28, 'None', mod]
    Migaku Retirement ['Migaku Retirement', 2020-12-16T17:41, 'None', mod]
    Minimal Theme ['867316254', 2022-04-22T09:33, 'None', '']
    Multi-field Batch Update ['1081479402', 2019-07-15T23:21, 'None', '']
    PassFail 2 Remove the Easy and Hard buttons ['876946123', 2022-07-14T13:39, 'None', '']
    Randomize Fonts ['1603486068', 2021-03-19T12:50, 'None', mod]
    ReMemorize Rescheduler with sibling and logging v142 ['323586997', 2020-11-19T21:27, 'None', mod]
    RefoldEase ['819023663', 2021-12-12T15:49, 'None', '']
    Resize images in editor ['1103084694', 2021-07-18T23:35, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T06:23, 'None', '']
    Show duplicates ['865767531', 2021-01-13T08:21, 'None', '']
    avgEase ['633293039', 2018-12-14T16:08, 'None', '']
    jlpt-stats ['1540467968', 2019-06-02T16:55, 'None', '']
    movie2anki ['1846227036', 2019-01-13T06:00, 'None', '']
    when is next learning card due today due ['563204849', 2021-12-06T07:06, 'None', '']

**Comment by Kosezu** [comment]
And the meta data from the json file:

{"name": "Leech Toolkit", "package": "368380974", "mod": 1671458283455}

**Comment by iamjustkoi** [comment]
Should hopefully be fixed in the most recent release ([v1.3.5](https://github.com/iamjustkoi/LeechToolkit/releases/tag/v1.3.5))!
Thanks again for the report!
